title: Page

pages:
  template:
    - section_hero
    - redirect

fields:
  title: title

  info:
    label: Hint
    type: info
    text: >
      Die Inhalte werden durch die einzelnen Unterseiten definiert.
